from contextlib import AbstractContextManager
from pathlib import Path
from typing import Any

class Config: ...

class MonkeyPatch:
    def setenv(self, name: str, value: str) -> None: ...
    def setitem(self, mapping: Any, name: str, value: Any) -> None: ...
    def setattr(self, target: Any, name: str, value: Any) -> None: ...
    def chdir(self, path: str | Path) -> None: ...

class RaisesContext(AbstractContextManager[Any]):
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc, tb) -> bool: ...

def raises(expected_exception: type[BaseException]) -> RaisesContext: ...
def skip(reason: str) -> None: ...
def importorskip(
    modname: str,
    minversion: str | None = None,
    reason: str | None = None,
) -> Any: ...
